### ISSUE TITLE
Scientific Notation

### ISSUE THREAD

**Issue by Igie** [peteroupc/Numbers#17]
Sorry to bother you but I can't figure out how to convert EFloat or EDecimal to scientific notation. the default ToString() only converts number to string, same with ToEngineeringString().

**Comment by peteroupc** [comment]
Can you explain in more detail what you seek to achieve, including examples of inputs and expected outputs?

Are you trying to get a format like the following?  9.9999 * 10^50.

The format returned by ToString and ToEngineeringString is not exactly scientific notation.  For example, ToString's documentation currently says: "The text string will be in exponential notation if the exponent is greater than 0 or if the number's first nonzero digit is more than five digits after the decimal point."

**Comment by Igie** [comment]
What I want is to display EFloat as scientific notation. For example 15001 represented as 1.5001e+4 or  1.5001e4. Is there a built in method? Surprisingly when I use ScaleByPowerOfTen on EDecimal, the default ToString starts showing scientific notation.

**Comment by peteroupc** [comment]
Indeed, ToString does not always show what you call "scientific notation"; this is to match the behavior in the [General Decimal Arithmetic Specification](http://speleotrove.com/decimal/daconvs.html#reftostr).  In particular, see the examples in the text.  Also, you can use ScaleByPowerOfTen on an EDecimal number as you found out to add more "digits" to an EDecimal and bring its exponent to greater than 0.  Finally, EFloat.ToString [converts the string to EDecimal](https://github.com/peteroupc/Numbers/blob/master/Numbers/PeterO/Numbers/EFloat.cs#L4351), then calls ToString, so much of the same discussion applies to EFloat as well.

**Comment by Igie** [comment]
Thank you for clarification.
