### ISSUE TITLE
EDecimal can't divide 1/x

### ISSUE THREAD

**Issue by burnsba** [peteroupc/Numbers#3]
```
static void Main(string[] args)
{
    Console.WriteLine(EDecimal.One.Divide(3).IsFinite);
}
```

running the program outputs:
    False

**Comment by peteroupc** [comment]
EDecimal's Divide method works as documented; see https://peteroupc.github.io/Numbers/docs/PeterO.Numbers.EDecimal.html.  It returns NaN "if the result can't be exact because it would have a nonterminating decimal expansion" (as is the case for 1 divided by 3); moreover, NaN isn't a finite number.
